<a href="https://colab.research.google.com/github/thomasvicente/Class-Projects/blob/main/PrincipalComponentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Written By: Thomas Vicente
#The following programs are for PS9, written in google colab, please separate the programs to run

In [8]:
#problem 2
import numpy as np

A = np.array([[1,2],[3,4]])

values, vectors = np.linalg.eig(A)

print('eigenvalues: ',values)
print('eigenvectors: ', vectors)

eigenvector1 = vectors[:, 0]
eigenvector2 = vectors[:, 1]
dot_product = np.dot(eigenvector1, eigenvector2)
print("Dot product:", dot_product)

eigenvalues:  [-0.37228132  5.37228132]
eigenvectors:  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Dot product: -0.17149858514250893


In [24]:
#3a
C = np.array([[5, -1, 2],
              [-1, 4, 0],
              [2, 0, 10]])

eigenvalues, eigenvectors = np.linalg.eig(C)

sorted_indices = np.argsort(eigenvalues)[::-1]
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]

std_deviations = np.sqrt(sorted_eigenvalues)

print('eigenvectors and values:','\n',sorted_eigenvectors, '\n\n', sorted_eigenvalues,'\n')
print("Standard deviations along the principal axes: \n", std_deviations)

eigenvectors and values: 
 [[-0.33754874  0.70741238  0.62098999]
 [ 0.05024382 -0.64522889  0.76233538]
 [-0.93996617 -0.28852626 -0.1822531 ]] 

 [10.71821466  5.09637431  3.18541103] 

Standard deviations along the principal axes: 
 [3.27386845 2.25751507 1.78477198]


In [32]:
#3b
C = np.array([[5, -1, 2],
              [-1, 4, 0],
              [2, 0, 10]])

eigenvalues, eigenvectors = np.linalg.eig(C)

A = eigenvectors
v = np.array([1, 2, 3]).reshape(-1, 1)
A_inv = np.linalg.inv(A)
a = np.dot(A_inv, v)
print('matrix a: \n',A)
print("Coefficients a1, a2, a3:", a)

matrix a: 
 [[-0.33754874  0.70741238  0.62098999]
 [ 0.05024382 -0.64522889  0.76233538]
 [-0.93996617 -0.28852626 -0.1822531 ]]
Coefficients a1, a2, a3: [[-3.05695963]
 [-1.44862417]
 [ 1.59890145]]
